# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Work/UH/1_FPGA/1_2022/2_ZCU111/3_Code/V10_5/V10_4.srcs/sources_1/bd/design_1/ip/design_1_usp_rf_data_converter_0_0_1/design_1_usp_rf_data_converter_0_0.xci
# IP: The module: 'design_1_usp_rf_data_converter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Work/UH/1_FPGA/1_2022/2_ZCU111/3_Code/V10_5/V10_4.gen/sources_1/bd/design_1/ip/design_1_usp_rf_data_converter_0_0_1/synth/design_1_usp_rf_data_converter_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_usp_rf_data_converter_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Work/UH/1_FPGA/1_2022/2_ZCU111/3_Code/V10_5/V10_4.gen/sources_1/bd/design_1/ip/design_1_usp_rf_data_converter_0_0_1/synth/design_1_usp_rf_data_converter_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_usp_rf_data_converter_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Work/UH/1_FPGA/1_2022/2_ZCU111/3_Code/V10_5/V10_4.gen/sources_1/bd/design_1/ip/design_1_usp_rf_data_converter_0_0_1/synth/design_1_usp_rf_data_converter_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_usp_rf_data_converter_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Work/UH/1_FPGA/1_2022/2_ZCU111/3_Code/V10_5/V10_4.srcs/sources_1/bd/design_1/ip/design_1_usp_rf_data_converter_0_0_1/design_1_usp_rf_data_converter_0_0.xci
# IP: The module: 'design_1_usp_rf_data_converter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Work/UH/1_FPGA/1_2022/2_ZCU111/3_Code/V10_5/V10_4.gen/sources_1/bd/design_1/ip/design_1_usp_rf_data_converter_0_0_1/synth/design_1_usp_rf_data_converter_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_usp_rf_data_converter_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Work/UH/1_FPGA/1_2022/2_ZCU111/3_Code/V10_5/V10_4.gen/sources_1/bd/design_1/ip/design_1_usp_rf_data_converter_0_0_1/synth/design_1_usp_rf_data_converter_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_usp_rf_data_converter_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Work/UH/1_FPGA/1_2022/2_ZCU111/3_Code/V10_5/V10_4.gen/sources_1/bd/design_1/ip/design_1_usp_rf_data_converter_0_0_1/synth/design_1_usp_rf_data_converter_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_usp_rf_data_converter_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
